---
- name: Make sure X-UI is created and running
  register: xui_result
  retries: 5
  until: xui_result is succeeded
  community.general.docker_container:
    name: "xui"
    image: "alireza7/x-ui:latest"
    hostname: "{{ xui_host }}"
    pull: yes
    state: "started"
    volumes:
      - "{{ docker_dir }}/xui/db/:/etc/x-ui/"
      - "{{ docker_dir }}/xui/cert/:/root/cert/"
    env:
      XRAY_VMESS_AEAD_FORCED: 'false'
    tty: true
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.9
    ports:
      - "54321:54321"
      - "8443:8443"
      - "8080:8080"
    restart_policy: unless-stopped